#!/bin/bash
#
# twist rake 1.0
# bellee@webit.de
# adam@webit.de




#hilfe
if [ -z $1 ]; then SHOWHELP="1"; fi
if [ "$1" == "--help" ]; then SHOWHELP="1"; fi
if [ "$1" == "-h" ]; then SHOWHELP="1"; fi

if [ "$SHOWHELP" == "1" ]
then
  echo "take 1.0 usage:"
  echo "$0 { [ f | i | l | u | p]  | [ pfad/zum/test ] | [ pfad/zum/test test_x ] }"
  exit
fi
# Was fuer ne Testart?
TESTKIND=$1

LINE="rake"

#if the first argument is a path, we scan it for "functionals", "units" etc
if [ -f "$1" ] #this means $1 is an existing path
then
  if [ -n "`echo $1 | grep integration`" ]
  then
    TESTKIND="integration" 
  elif [ -n "`echo $1 | grep functional`" ]
  then
    TESTKIND="functionals" 
  elif [ -n "`echo $1 | grep unit`" ]
  then
    TESTKIND="units" 
  elif [ -n "`echo $1 | grep lib`" ]
  then
    TESTKIND="libs" 
  elif [ -n "`echo $1 | grep plugins`" ]
  then
    TESTKIND="plugins" 
  fi

  LINE="rake test:$TESTKIND TEST=$1"
  if [ "$2" != "" ]
  then
    LINE=$LINE" TESTOPTS=-n$2"
  fi
else #the first argument is the testkind
  if [ "${TESTKIND:0:1}" = "f" ];then TESTKIND="functionals"; fi 
  if [ "${TESTKIND:0:1}" = "i" ];then TESTKIND="integration"; fi 
  if [ "${TESTKIND:0:1}" = "u" ];then TESTKIND="units"; fi 
  if [ "${TESTKIND:0:1}" = "l" ];then TESTKIND="libs"; fi 
  if [ "${TESTKIND:0:1}" = "p" ];then TESTKIND="plugins"; fi 

  LINE="rake test:$TESTKIND"
  if [ "$2" != "" ]
  then
    FILE=$(echo "$2"|sed -e "s/^\///")
    LINE=$LINE" TEST=$FILE"
  fi
  if [ "$3" != "" ]
  then
    LINE=$LINE" TESTOPTS=-n$3"
  fi
fi

$LINE
